# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "zpool/root";
      options = [ "zfsutil" ];
      fsType = "zfs";
    };

  fileSystems."/nix" =
    { device = "zpool/nix";
      options = [ "zfsutil" ];
      fsType = "zfs";
    };

  fileSystems."/var" =
    { device = "zpool/var";
      options = [ "zfsutil" ];
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "zpool/home";
      options = [ "zfsutil" ];
      fsType = "zfs";
    };

  fileSystems."/games" =
    { device = "zpool/games";
      options = [ "zfsutil" ];
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/7CC7-269E";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices =
    [{
      device = "/dev/disk/by-partuuid/05122b8e-c9be-44a4-ac03-fbc22295334e"; 
      randomEncryption = true;
    }];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
